import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 880 } });
await page.goto('file:///C:/Projects/astro-blog/design-demos/16-synthesis.html', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.setItem('demo16dark', ''));
await page.waitForTimeout(700);
await page.screenshot({ path: 'design-demos/shots/_16-light.jpg', fullPage: true, type: 'jpeg', quality: 75 });
await page.click('#theme');
await page.waitForTimeout(500);
await page.screenshot({ path: 'design-demos/shots/_16-dark.jpg', fullPage: true, type: 'jpeg', quality: 75 });
await browser.close();
console.log('shot 16 light+dark');
